#ifndef CONSTANTS_H_
#define CONSTANTS_H_

#define NUMBER_OF_BASIS_FUNCTIONS (CONVERGENCE_ORDER*(CONVERGENCE_ORDER+1)/2)
#define NUMBER_OF_QUANTITIES 3

#define NUMBER_OF_DOFS (NUMBER_OF_BASIS_FUNCTIONS*NUMBER_OF_QUANTITIES)

#if !defined(CONVERGENCE_ORDER)
#error CONVERGENCE_ORDER must be set.
#elif CONVERGENCE_ORDER == 2
#define PADDED_GLOBAL_MATRICES_LENGTH 8
#elif CONVERGENCE_ORDER == 3
#define PADDED_GLOBAL_MATRICES_LENGTH 8
#elif CONVERGENCE_ORDER == 4
#define PADDED_GLOBAL_MATRICES_LENGTH 16
#elif CONVERGENCE_ORDER == 5
#define PADDED_GLOBAL_MATRICES_LENGTH 16
#elif CONVERGENCE_ORDER == 6
#define PADDED_GLOBAL_MATRICES_LENGTH 24
#elif CONVERGENCE_ORDER == 7
#define PADDED_GLOBAL_MATRICES_LENGTH 32
#elif CONVERGENCE_ORDER == 8
#define PADDED_GLOBAL_MATRICES_LENGTH 40
#elif CONVERGENCE_ORDER == 9
#define PADDED_GLOBAL_MATRICES_LENGTH 48
#elif CONVERGENCE_ORDER == 10
#define PADDED_GLOBAL_MATRICES_LENGTH 56
#elif CONVERGENCE_ORDER == 11
#define PADDED_GLOBAL_MATRICES_LENGTH 72
#elif CONVERGENCE_ORDER == 12
#define PADDED_GLOBAL_MATRICES_LENGTH 80
#endif

#if !defined(PADDED_GLOBAL_MATRICES_LENGTH)
#define NUMBER_OF_PADDED_DOFS (NUMBER_OF_BASIS_FUNCTIONS*NUMBER_OF_QUANTITIES)
#else
#define NUMBER_OF_PADDED_DOFS (NUMBER_OF_BASIS_FUNCTIONS*8)
#endif

#endif // CONSTANTS_H_
