CC = icc
CFLAGS = -qopenmp -DSTREAM_ARRAY_SIZE=72000000


all: stream_c.exe

stream_c.exe: stream.c
	$(CC) $(CFLAGS) stream.c -o stream_c.exe

clean:
	rm -f stream_c.exe *.o

# an example of a more complex build line for the Intel icc compiler
stream.icc: stream.c
	icc -qopenmp -DSTREAM_ARRAY_SIZE=72000000 stream.c -o stream.omp.AVX2.72M.20x.icc
